### ISSUE TITLE
Not Working With Fragment

### ISSUE THREAD

**Issue by arafeh94** [ludovicroland/carousel-android#1]
I test your example code with fragment and it not working at all only 1 item is showing

**Comment by ludovicroland** [comment]
@arafeh94 : Thx for your feedback. I'm going to check that :)

**Comment by ludovicroland** [comment]
@arafeh94 : I have updated the sample app with two new screens.
- The first one is an activity with a static fragment (the fragment is set directly into the layout).
- The second one is an activity with a dynamic fragment (the fragment is set through a transaction).

Everything seems to work correctly without any update of the library. Please check the sample app again.
