### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by MuhammadKamal** [ludovicroland/carousel-android#5]
07-02 07:24:56.362: E/AndroidRuntime(10820): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.digitalaria.gama.sample.carousel/com.digitalaria.gama.sample.carousel.SampleCarouselActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class com.digitalaria.gama.carousel.Carousel

**Comment by ludovicroland** [comment]
Please the readme file. The package name should be `fr.rolandl.carousel.Carousel`.
