### ISSUE TITLE
While compiling the Example

### ISSUE THREAD

**Issue by MuhammadKamal** [ludovicroland/carousel-android#6]
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by ludovicroland** [comment]
@MuhammadKamal can you provide more information please ?

**Comment by MuhammadKamal** [comment]
While i'm importing the example this error shows.

**Comment by ludovicroland** [comment]
In the `build.gradle` file of the `library` module, just comment the following line :

```
apply from: 'maven_push.gradle'
```

**Comment by MuhammadKamal** [comment]
@ludovicroland 
Resolved

**Comment by MuhammadKamal** [comment]
Thanks for this library it's looks awesome.
